[server.pv.addon.disks.error]
erase_wrong_item = "&cCan't erase this item"
get_track_fail = "&cFailed to get the track: %s"
not_a_record = "&cYou need have a record in your hand to burn it"
unknown_subcommand = "&cUnknown subcommand. Available commands: %s"

[server.pv.addon.disks.usage]
burn = "&cUsage: /disks burn <url> [label]"

[server.pv.addon.disks.arg]
url = "<url>"
label = "[label]"

[server.pv.addon.disks.actionbar]
track_not_found = "Track not found: %s"
playing = "Now playing: %s"

[server.pv.addon.disks.success]
erase = "&aCustom audio erased"
burn = "&aDisc burned. Label: %s"

[client.pv.activation]
disks = "Disks"
