[server.pv.addon.disks.error]
erase_wrong_item = "&cЭтот предмет нельзя очистить"
get_track_fail = "&cНе получилось получить трек: %s"
not_a_record = "&cЧтобы прожечь диск вам нужно держать его в руке"
unknown_subcommand = "&cТакой команды нет. Доступные команды: %s"

[server.pv.addon.disks.usage]
burn = "&cИспользование: /disc burn <ссылка> [название]"

[server.pv.addon.disks.arg]
url = "<ссылка>"
label = "[название]"

[server.pv.addon.disks.actionbar]
track_not_found = "Трек не найден: %s"
playing = "Сейчас играет: %s"

[server.pv.addon.disks.success]
erase = "&aДиск очищен"
burn = "&aДиск прожжен. Название: %s"

[client.pv.activation]
disks = "Диски"